# ja.toml - v10.1.37.2
[addon]
appDesc = ''ウェブからビデオをダウンロード''
restore_purchase_button = ''購入を復元''
get_premium_button = ''プレミアムに更新''
back = ''戻る''
rm_notifications_all = ''通知をすべて閉じる''
waiting_for_media = ''メディアを待機中''
nomedia_title = ''お探しのものが見つかりませんか?''
nomedia_description = ''メディアを検出するためにはビデオを再生してください。動画が見つからない場合には報告してください''
nomedia_reload_button = ''強制検出''
nomedia_reload_button_tooltip = ''強制リロード(クッキーを削除)''
show_nomedia_button = ''ビデオが見つからないですか?''
show_nomedia_button_tooltip = ''ビデオが見つからない場合はここをクリック''
setting_button_tooltip = ''設定…''
history_button_tooltip = ''ダウンロード履歴を見る''
show_all_history_button = ''全てを表示する''
complete_title = ''完了''
hide_complete_button = ''隠す''
translate_button_tooltip = ''VDHの翻訳にご協力下さい''
help_button_tooltip = ''ヘルプ''
open_source_tab_button_tooltip = ''ソースタブを開く''
retry_download_button_tooltip = ''再ダウンロード''
delete_file_button_tooltip = ''ファイルを削除する''
download_directory_button_tooltip = ''ダウンロードフォルダーを表示''
clear_downloaded_tooltip = ''ダウンロード履歴をクリア''
show_in_popup_button_tooltip = ''ポップアップで表示''
show_in_sidebar_button_tooltip = ''サイドバーに表示''
video_not_playing_button_tooltip = ''ビデオが再生されませんか?''
play = ''再生''
warn_drm_tooltip = ''DRMが特定されました''
version_title = ''バージョン''
account_title = ''アカウント''
one_hundred_downloads_title = ''100本の動画をダウンロードしました！''
leave_review_description = ''Video DownloadHelper をお楽しみいただければ幸いです :) 素敵なレビューを書きませんか?''
leave_review_button = ''レビューする''
account_status = ''ステータス''
account_status_premium = ''プレミアム ($1)''
free_account = ''無料プラン''
copy_to_clipboard = ''クリップボードにコピー''
my_account_button = ''自分のアカウント''
download_title = ''ダウンロードしたファイル''
show_notification = ''ダウンロードが完了したら通知を表示する''
max_parallel_downloads = ''最大同時ダウンロード数''
saveas_detected_warning = ''ダウンロード完了時に、ブラウザーの「名前を付けて保存」のダイアログを表示しました。ブラウザ上でこのオプションを解除することをお勧めします。''
change_saveas_setting = ''設定を変更する''
download_directory_title = ''保存したフォルダ''
download_directory_description = ''ビデオはブラウザのデフォルトのダウンロードフォルダにダウンロードされます。サブフォルダを指定することも可能です。ウェブサイトごとのダウンロードフォルダはスマートネーミングエディタで設定できます。''
change_browser_download_directory = ''ブラウザのダウンロードフォルダを変更する''
bad_download_subdirectory_warning = ''指定したサブフォルダは無効です。''
download_subdirectory = ''ダウンロードサブフォルダ''
private_browsing_title = ''プライベートブラウジング''
private_browsing_warning = ''Video DownloadHelper はプライベート/シークレット ウィンドウでは無効です。オプションを手動で設定する必要があります。（任意）''
private_browsing_notifications = ''プライベートダウンロードの通知を表示する''
private_browsing_button = ''プライベートブラウジングの設定を変更する''
throttle_youtube = ''YouTubeの速度を制限する（ダウンロード速度は遅くなりますが、ブロックされる可能性が低くなります）''
prefer_original_audio = ''オリジナルの言語の音声を利用する''
prefer_hls = ''HLSを使用する''
settings_history_title = ''履歴''
transient_history_description = ''完了したダウンロードをパネルに表示する''
history_limit = ''日後に自動でダウンロード履歴を削除する''
appearance_title = ''外観''
theme_title = ''テーマ''
theme_light = ''ライトモード''
theme_dark = ''ダークモード''
theme_system = ''システム標準''
popup_size_title = ''ウィンドウサイズ''
popup_size_small = ''小''
popup_size_medium = ''中''
popup_size_big = ''大''
panel_position_title = ''パネルの位置''
use_popup = ''ポップアップで表示''
use_sidebar = ''サイドバーで表示''
behavior_title = ''動作''
controls_title = ''操作''
show_in_context_menu = ''ページ内を右クリックしてコマンドにアクセスします。''
restart_addon = ''DownloadHelperを再起動する''
reset_settings = ''設定を初期値に戻す''
prefered_quality = ''推奨動画品質''
prefered_quality_highest = ''最高画質 （低速・高解像度）''
prefered_quality_1080p = ''1080p （デフォルト・バランス重視）''
prefered_quality_720p = ''720p （高速・低解像度）''
prefer_mkv = ''可能な場合はMKV形式でダウンロード''
preview_mode_title = ''メディアのプレビュー''
preview_mode_none = ''無効''
preview_mode_video = ''ショート動画プレビュー''
preview_mode_image = ''画像''
history_title = ''ダウンロード履歴''
history_warning = ''ダウンロード履歴を記録しません。Video DownloadHelper にダウンロード履歴を記録しますか?''
history_warning_2 = ''心配ありません。すべての履歴を残します。あなたのプライバシーを尊重します。''
enable_history = ''履歴を有効にする''
clear_history = ''履歴を消す''
disable_history = ''履歴を無効にする''
no_downloads_yet = ''ダウンロードはありません''
download_failed = ''ダウンロードに失敗しました''
download_failed_description = ''何か問題があったようです。エラーを報告してください。原因究明に全力を尽くします。(URLの秘密は守られます。我々はあなたをトラッキングしません!)''
download_interrupted = ''ダウンロードが中断されました''
download_interrupted_description = ''ファイルのダウンロードは成功しましたが、ネットワークの問題が発生しました。ファイルが予想より短い可能性があります。可能な限り多くのウェブサイトをサポートするよう努めていますので、この問題を報告していただけると大変助かります。（匿名で報告できます！）''
download_with_drm_failed_description = ''何か問題があったようです。ビデオ内にDRMがあるようです。DRM付きビデオはサポートしておりません。''
no_youtube = ''YouTubeからのダウンロードはできません''
no_youtube_description = ''申し訳ありませんが、Chrome ウェブストアでは YouTube 動画のダウンロード用の拡張機能が許可されないため、この機能を Chrome バージョンの拡張機能に含めることができませんでした。''
no_youtube_description_2 = ''Firefox または Microsoft Edge をご利用ください''
premium_required = ''プレミアムステータスが必要''
premium_yt_required_description = ''プレミアム未加入の場合、次のYouTubeのダウンロードが可能になるまで2時間お待ちください。''
premium_hls_required_description = ''プレミアムステータスなしでは、前回のHLS ダウンロードから120分後にのみ可能です。''
premium_all_required_description = ''プレミアムステータスなしでは、前回のダウンロードから2時間後にのみ可能です。''
youtube_too_many_downloads = ''YouTubeがブロックされているようです''
youtube_too_many_downloads_description = ''YouTubeでは、リクエストできる動画の数に制限がかかる場合があります。残念ながら、これについては対応できません。後ほど再度お試しください。''
stop = ''停止''
cancel = ''キャンセル''
copy_url = ''URLをコピー''
always_copy_url = ''常にURLをコピーする''
download_button = ''ダウンロード''
download_as_button_and_menu = ''名前を付けてダウンロード''
rename_short = ''名前を変更''
always_download_as_menu = ''常にダウンロード形式を…''
download_audio_button = ''オーディオ''
download_audio_and_video_menu = ''オーディオとビデオをダウンロードする''
download_audio_only_menu = ''オーディオをダウンロード''
audio_only_for_this_website = ''このウェブサイトでは常に音声のみ利用する''
details = ''詳細''
report = ''報告''
reporting = ''報告中''
reported_thankyou = ''ありがとうございました！''
not_playing_title = ''ビデオが再生されませんか？''
not_playing_broken_title = ''オーディオかビデオに問題がありますか？''
not_playing_broken_description = ''問題のあるメディアを報告する。問題究明に全力をつくします。(URLの秘密は守られます。我々はあなたをトラッキングしません！)''
not_playing_broken_solution_title = ''最新のビデオプレイヤーを試す''
not_playing_broken_solution_windows_1 = ''VLCをおすすめします''
not_playing_broken_solution_mac_1 = ''IINAをおすすめします''
not_playing_broken_solution_2 = ''安全でオープンな最新バージョンです''
not_playing_default_player = ''ビデオプレイヤーをシステムのデフォルトに設定する''
not_playing_default_player_solution_windows = ''In Windows' "Control Panel", click on "Default Programs", and change the default programs for your player.''
not_playing_default_player_solution_mac = ''Open download directory right-click on the video file. Click 'Get Info'. In the 'Open With' section, select IINA. Click the 'Change All' button.''

[web]
back = ''戻る''
header_help = ''ヘルプ''
header_ask_question = ''質問する''
activate_title = ''アクティベーション''
activate_pending = ''進行中''
activate_success = ''成功しました''
activate_error = ''エラー''
activate_no_addon_found = ''アドオンが見つかりません。インストールされていますか？''
activate_no_method_found = ''該当する方法は見つかりませんでした''
activate_help_me = ''ヘルプ''
issue_title = ''購入を復元''
issue_submit = ''送信''
issue_thank_you = ''ありがとうございました''
issue_enter_email = ''購入を復元するため、ライセンス購入時に使ったメールアドレスを入力してください。''
issue_email_sent = ''製品をアクティベートするためのEメールを送信しました。''
issue_or_digit = ''もしくは送信した6桁のコードを入力してください。''
issue_just_digit = ''6桁のコードを入力してください''
issue_i_have_a_code = ''すでにコードを持っている場合ここをクリックしてください''
issue_i_have_a_key = ''(ライセンスキーをお持ちの方はここをクリックしてください)''
issue_key = ''Video DownloadHelperのライセンスキーを入力してください：''
landing_text1 = ''どんなウェブサイトからでも、どんなビデオでもダウンロードできます!''
landing_text2 = ''1000以上のウェブサイトで利用できます''
landing_text3 = ''700万人のユーザーに信頼されています''
landing_text4 = ''ストアで4.5の評価を得ています''
landing_install_for_google = ''Chromeにインストールする''
landing_install_for_mozilla = ''Firefoxにインストールする''
landing_install_for_microsoft = ''Edgeにインストールする''
landing_feature1_title = ''フルスピードでHDダウンロード''
landing_feature1_description = ''最速、最高画質でビデオをインストールできます。我々は最も速いダウンロードエンジンです。''
landing_feature2_title = ''ビデオをアーカイブ''
landing_feature2_description = ''好きなビデオを保存できます。''
landing_feature3_title = ''ライブストリームサポート''
landing_feature3_description = ''ライブストリームのオフライン鑑賞を楽しめます。遅延に困ることはもうありません。''
landing_feature4_title = ''オーディオダウンロード''
landing_feature4_description = ''ビデオからオーディオを抽出し、MP3やポッドキャストに組み込めます。''
premium_hero1 = ''一度のお支払いで永久利用できます''
premium_hero2 = ''Video DownloadHelperの永久利用を始める''
premium_hero3 = ''制限なしで、ダウンロードしたいだけできます''
welcome_text = ''もうビデオを失うことはありません!''
welcome_pin_message = ''アドオンのアイコンをツールバーにピン止めする''
